# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: fanflip
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-01-25T00-19-54Z
    container_name: minio1
    ports:
      - 9100:9000
      - 9101:9001
    environment:
      MINIO_ROOT_USER: minio123
      MINIO_ROOT_PASSWORD: minio123
      TZ: 'America/Mexico_City'
    volumes:
      - miniodata:/data
    command: server --console-address ":9001" /data
    restart: 'no'
    networks:
      - fanflip-net

volumes:
  tmp:
  applogs:

  pgdata:
    driver: local
  miniodata:
    driver: local

networks:
  fanflip-net:
    driver: bridge
