commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: demo

resources:
  - namespace.yml
  # Individual apps
  - gateway-k8s/gateway-deployment.yml
  - gateway-k8s/gateway-service.yml
  - gateway-k8s/gateway-postgresql.yml
  - gateway-k8s/gateway-elasticsearch.yml
  - finance-k8s/finance-deployment.yml
  - finance-k8s/finance-service.yml
  - finance-k8s/finance-postgresql.yml
  - finance-k8s/finance-elasticsearch.yml
  - multimedia-k8s/multimedia-deployment.yml
  - multimedia-k8s/multimedia-service.yml
  - multimedia-k8s/multimedia-postgresql.yml
  - multimedia-k8s/multimedia-elasticsearch.yml
  - interactions-k8s/interactions-deployment.yml
  - interactions-k8s/interactions-service.yml
  - interactions-k8s/interactions-postgresql.yml
  - interactions-k8s/interactions-elasticsearch.yml
  - profile-k8s/profile-deployment.yml
  - profile-k8s/profile-service.yml
  - profile-k8s/profile-postgresql.yml
  - profile-k8s/profile-elasticsearch.yml
  - admin-k8s/admin-deployment.yml
  - admin-k8s/admin-service.yml
  - admin-k8s/admin-postgresql.yml
  - admin-k8s/admin-elasticsearch.yml
  - admin-k8s/jwt-secret.yml
  # messagebroker
  - messagebroker-k8s/kafka.yml
  # service discovery eureka/consul
  - registry-k8s/consul.yml
  - registry-k8s/consul-config-loader.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
