apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: monsterdam/gateway
      context: ../gateway
      jib: {}
    - image: monsterdam/finance
      context: ../finance
      jib: {}
    - image: monsterdam/multimedia
      context: ../multimedia
      jib: {}
    - image: monsterdam/interactions
      context: ../interactions
      jib: {}
    - image: monsterdam/profile
      context: ../profile
      jib: {}
    - image: monsterdam/admin
      context: ../admin
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
