apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: demo
type: Opaque
data:
  secret: WVdKa04yUmlNamRqTXpBME5tUmxNREJsTUdNMVpqaGlPR1ZoWmpKbE1qWTBOems1TTJOak5EVXhNVGt6Wm1SbE4yVTRaVGczWlRJNE1qQXpOams0WXprMlptRmhaVEExWkROaE56QXlOV1EyWmpNNFpERTBNR001T0RBMk5HRTFZekU1WlE9PQ==
